-- Migration: SUPERSEDED — intentionally a no-op. Do not add columns here.
--
-- An earlier, parallel credential scheme proposed storing an application
-- AES-256-GCM encrypted Google Drive refresh token in a new
-- `drive_accounts.refresh_token_encrypted` column using an `ENCRYPTION_KEY`
-- Edge Function secret.
--
-- That scheme is NOT part of the MyDrive backend architecture and is no longer
-- used anywhere in this repository (google-oauth-callback included). The
-- authoritative storage path is Supabase Vault:
--
--   google-oauth-callback
--     -> admin_store_drive_refresh_token(p_drive_account_id, p_refresh_token)
--     -> Supabase Vault
--     -> drive_accounts.refresh_token_secret_id
--     -> worker_lookup_drive_refresh_token()
--     -> drive-replicate
--
-- This migration deliberately performs NO schema change:
--   * it must not create `refresh_token_encrypted`
--   * it must not introduce or depend on `ENCRYPTION_KEY`
--   * it does NOT drop anything that may already exist in the live database
--     (dropping columns is destructive and out of scope)
--
-- If `refresh_token_encrypted` exists in the live database it is simply
-- unused; remove it manually only as a separate, reviewed operation.
